### Introduction to Tensors 
1. Introduction to Tensors 
2. Operations Supported by Tensors 

In [2]:
import os
os.environ["TF_ENABLE_ONEDNN_OPTS"] = "0"
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

In [3]:
import tensorflow as tf 
import numpy as np 

In [12]:
# Tensors dimensions 
# 0 (Scalar) 
a = tf.constant(5)
print(a)

# 1 (Vector)
vector = tf.constant([4.0, 2.0, 3.0, 4.1], dtype= 'float32')
print(vector)

# 2 (Matrix)
matrix = tf.constant([[1.0, 2.0, 3.0],
                      [21.1, 3.0, 4.0]], 
                      dtype= tf.float32)
print(matrix)


tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([4.  2.  3.  4.1], shape=(4,), dtype=float32)
tf.Tensor(
[[ 1.   2.   3. ]
 [21.1  3.   4. ]], shape=(2, 3), dtype=float32)


In [19]:
# 3D Tensors
D_tensors = tf.constant([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],

    [[10, 11, 12],
     [13, 14, 15], 
     [16, 17, 18]],

    [[19, 20, 21],
     [22, 23, 24],
     [25, 26, 27]]
], dtype= tf.int32)

print(D_tensors)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]], shape=(3, 3, 3), dtype=int32)


In [24]:
# Converts 3D tensors into numpy elements 
np.array(D_tensors)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]], dtype=int32)

In [26]:
print(type(D_tensors.numpy()))

<class 'numpy.ndarray'>


### Tensor operations
1. Addition
2. Substraction
3. Element - wise multiplicaiton
4. Multiplication


In [33]:
a = tf.constant([[2, 4], 
                [4, 8]], dtype= tf.int32)

b = tf.constant([[6, 12],
                 [12, 24]], dtype= tf.int32)

print(f'Matrix addition: {a + b}')
print(f'Matrix Element-Multiplication: {a * b}')
print(f'Multiplication: {a @ b}')
print(f'Matrix Subtraction: {a - b}')

Matrix addition: [[ 8 16]
 [16 32]]
Matrix Element-Multiplication: [[ 12  48]
 [ 48 192]]
Multiplication: [[ 60 120]
 [120 240]]
Matrix Subtraction: [[ -4  -8]
 [ -8 -16]]


In [40]:
# Tensors some in-built operations 
x = tf.constant([[1, 2, 3], 
                 [4, 5, 6]], dtype= tf.int32)

y = tf.constant([[4, 5], 
                 [8, 9],
                 [10, 11]], dtype= tf.int32)

print(f'Matrix Multiplication: {tf.matmul(x, y)}')
print(f'Max value in Matrix: {tf.reduce_max(y)}') #Max value in matrix 
print(f'Max value index from Matrix: {tf.math.argmax(y)}') #Max value index in matrix
# Compute Activation functions in matrix 
# ReLU activation 
print(f'ReLU activation function: {tf.nn.relu(y)}')
# SoftMax activation
#print(f'Softmax activation function: {tf.nn.softmax(x)}')
#print(f'Softmax activation function: {tf.nn.softmax(y)}')

Matrix Multiplication: [[ 50  56]
 [116 131]]
Max value in Matrix: 11
Max value index from Matrix: [2 2]
ReLU activation function: [[ 4  5]
 [ 8  9]
 [10 11]]
