### Introduction to Tensors 
1. Introduction to Tensors 
2. Operations Supported by Tensors 

In [1]:
import os
os.environ["TF_ENABLE_ONEDNN_OPTS"] = "0"
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

In [2]:
import tensorflow as tf 
import numpy as np 

In [3]:
# Tensors dimensions 
# 0 (Scalar) 
a = tf.constant(5)
print(a)

# 1 (Vector)
vector = tf.constant([4.0, 2.0, 3.0, 4.1], dtype= 'float32')
print(vector)

# 2 (Matrix)
matrix = tf.constant([[1.0, 2.0, 3.0],
                      [21.1, 3.0, 4.0]], 
                      dtype= tf.float32)
print(matrix)


tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([4.  2.  3.  4.1], shape=(4,), dtype=float32)
tf.Tensor(
[[ 1.   2.   3. ]
 [21.1  3.   4. ]], shape=(2, 3), dtype=float32)


2025-11-08 12:13:26.226010: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


In [4]:
# 3D Tensors
D_tensors = tf.constant([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],

    [[10, 11, 12],
     [13, 14, 15], 
     [16, 17, 18]],

    [[19, 20, 21],
     [22, 23, 24],
     [25, 26, 27]]
], dtype= tf.int32)

print(D_tensors)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]], shape=(3, 3, 3), dtype=int32)


In [5]:
# Converts 3D tensors into numpy elements 
np.array(D_tensors)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]], dtype=int32)

In [6]:
print(type(D_tensors.numpy()))

<class 'numpy.ndarray'>


### Tensor operations
1. Addition
2. Substraction
3. Element - wise multiplicaiton
4. Multiplication


In [7]:
a = tf.constant([[2, 4], 
                [4, 8]], dtype= tf.int32)

b = tf.constant([[6, 12],
                 [12, 24]], dtype= tf.int32)

print(f'Matrix addition: {a + b}')
print(f'Matrix Element-Multiplication: {a * b}')
print(f'Multiplication: {a @ b}')
print(f'Matrix Subtraction: {a - b}')

Matrix addition: [[ 8 16]
 [16 32]]
Matrix Element-Multiplication: [[ 12  48]
 [ 48 192]]
Multiplication: [[ 60 120]
 [120 240]]
Matrix Subtraction: [[ -4  -8]
 [ -8 -16]]


In [8]:
# Tensors some in-built operations 
x = tf.constant([[1, 2, 3], 
                 [4, 5, 6]], dtype= tf.int32)

y = tf.constant([[4, 5], 
                 [8, 9],
                 [10, 11]], dtype= tf.int32)

print(f'Matrix Multiplication: {tf.matmul(x, y)}')
print(f'Max value in Matrix: {tf.reduce_max(y)}') #Max value in matrix 
print(f'Max value index from Matrix: {tf.math.argmax(y)}') #Max value index in matrix
# Compute Activation functions in matrix 
# ReLU activation 
print(f'ReLU activation function: {tf.nn.relu(y)}')
# SoftMax activation
#print(f'Softmax activation function: {tf.nn.softmax(x)}')
#print(f'Softmax activation function: {tf.nn.softmax(y)}')

Matrix Multiplication: [[ 50  56]
 [116 131]]
Max value in Matrix: 11
Max value index from Matrix: [2 2]
ReLU activation function: [[ 4  5]
 [ 8  9]
 [10 11]]


In [15]:
# Tensors shape, dimensions, Rank, Size (No. of elements)
p = tf.constant([[[1, 2, 3], 
                  [4, 5, 6],
                  [7, 8, 9]],

                  [[10, 11, 12], 
                   [13, 14, 15],
                   [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]
                ], dtype= tf.int32)

print(f'Tensor shape: {p.shape}')
print(f'Tensor rank: {tf.rank(p)}')
print(f'Tensor Dimensions: {p.ndim}')
print(f'No. of elements in Tensor: {tf.size(p)}')

Tensor shape: (3, 3, 3)
Tensor rank: 3
Tensor Dimensions: 3
No. of elements in Tensor: 27


In [25]:
# Indexing: Single and Multiple Dimensional 

# Single Axis 
vector = tf.constant([2, 3, 4, 5, 6, 7, 8], dtype= tf.int32)

vector = vector.numpy()

print(f'Element after index 2: {vector[2:]}')
print(f'Element before index 4: {vector[:4]}')
print(f'Every odd Element: {vector[1::2]}')
print(f'Reverse Tensor list: {vector[::-1]}')

Element after index 2: [4 5 6 7 8]
Element before index 4: [2 3 4 5]
Every odd Element: [3 5 7]
Reverse Tensor list: [8 7 6 5 4 3 2]


In [36]:
# Multiple Dimensional 
matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]]).numpy()

print(f'First Row Elements: {matrix[0, :]}')
print(f'Second Row Elements: {matrix[1, :]}')
print(f'First Column Elements: {matrix[:, 0]}')
print(f'Second Column Elements: {matrix[:, 1]}')
print(f'Second Row last elment: {matrix[1, -1:]}')
print(f'Second Column last element: {matrix[-1:, 1]}')

First Row Elements: [1 2 3]
Second Row Elements: [4 5 6]
First Column Elements: [1 4 7]
Second Column Elements: [2 5 8]
Second Row last elment: [6]
Second Column last element: [8]


In [40]:
# Tensor Reshaping 
tensor1 = tf.constant([
    [[1, 2, 3],
     [4, 5, 6], 
     [-1, 2, 4]],

    [[3, 4, 5],
    [6, 7, 8],
    [10, 11, 12]]
],dtype= tf.int32)

reshaped1 = tf.reshape(tensor1, [9, 2])

print('Tensor shape: ', tensor1.shape)
print('Reshaped Tensor Details: ', reshaped1)

# Flatten tensor 
flatten = tf.reshape(tensor1, [-1])
print('Flatten tensor: ', flatten)


Tensor shape:  (2, 3, 3)
Reshaped Tensor Details:  tf.Tensor(
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [-1  2]
 [ 4  3]
 [ 4  5]
 [ 6  7]
 [ 8 10]
 [11 12]], shape=(9, 2), dtype=int32)
Flatten tensor:  tf.Tensor([ 1  2  3  4  5  6 -1  2  4  3  4  5  6  7  8 10 11 12], shape=(18,), dtype=int32)


In [41]:
tensor2 = tf.constant([
    [[1, 2, 3, 10, 7],
     [4, 5, 6, 8, 10]],
    
    [[11, 12, 13, 11, 12],
     [15, 16, 17, 13, 12]],

    [[21, 22, 23, 24, 25],
     [24, 25, 26, 27, 28]],
], dtype= tf.int32)

reshape2 = tf.reshape(tensor2, [3 * 2, 5])
reshape3 = tf.reshape(tensor2, [3, -1])

print('Reshape tensor into (6, 5): ', reshape2)
print('Reshape tensor into (3, 10): ', reshape3)

Reshape tensor into (6, 5):  tf.Tensor(
[[ 1  2  3 10  7]
 [ 4  5  6  8 10]
 [11 12 13 11 12]
 [15 16 17 13 12]
 [21 22 23 24 25]
 [24 25 26 27 28]], shape=(6, 5), dtype=int32)
Reshape tensor into (3, 10):  tf.Tensor(
[[ 1  2  3 10  7  4  5  6  8 10]
 [11 12 13 11 12 15 16 17 13 12]
 [21 22 23 24 25 24 25 26 27 28]], shape=(3, 10), dtype=int32)
